--Comando IIF

SELECT C.CONTRATO,C.TITULO, U.NOME,
IIF(C.STATUS = 1, ‘Aprovado’,(IIF (C.STATUS = 3, ‘Cancelado’, ‘Outros’)))AS STATUS_CONTRATO
FROM contratowf C
INNER JOIN USUARIOS U
ON C.OWNERID = U.ID
where C.ID = 11111111 AND C.OWNERID = 22222222

--Utilizando DATEDIFF – Diferença entre 2 datas

SELECT TOP 10000 MENSAGEM,datediff(minute,DATAENTRADA,DATAPROCESSAMENTO) [minutos],
ENTRADASAIDA,ID,DATAENTRADA,DATAPROCESSAMENTO,DATAPROCESSINICIO,TAMANHO
FROM BrokerMensagem
WHERE DATAENTRADA BETWEEN ‘2017-01-31 19:00:00.000’
AND ‘2017-01-31 23:59:00.000’
and datediff(minute,DATAENTRADA,DATAPROCESSAMENTO) > 500
ORDER BY TAMANHO DESC